import '@radix-ui/themes/styles.css';
import type { Metadata } from 'next'
import './globals.css'
import { Theme } from '@radix-ui/themes';
import Navbar from './components/Navbar'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Theme appearance='light' accentColor='teal' >
          <Navbar />
          <main className='p-4'>
            {children}
          </main>
        </Theme>
      </body>
    </html>
  )
}
